import Head from "next/head";
import { Space_Grotesk } from "next/font/google";

const inter = Space_Grotesk({ subsets: ["latin"] });

import HomePage from "@/components/HomePage";
import SkillsSection from "@/components/SkillsSection";
import ProjectOne from "@/components/ProjectOne";
import SideBar from "@/components/SideBar";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Victor Azzolini Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <SideBar />
        <HomePage />
        <SkillsSection />
        <ProjectOne />
        <Contact/>
      </main>
    </>
  );
}

require('dotenv').config()